### ISSUE TITLE
When will you release the code?

### ISSUE THREAD

**Issue by morizin** [mlpc-ucsd/CoaT#1]
I am very interested in your project. i want to know when will your team releases the code with pre-trained model please

**Comment by xwjabc** [comment]
> I am very interested in your project. i want to know when will your team releases the code with pre-trained model please

Thank you for your interest in our project! We are preparing the code repo now and plan to release a version of the code and pretrained models by the end of this week. Stay tuned!

---
**Update**: I found a bug in my code just now (an incorrect order in concatenation of cls_token and img_tokens). The release date would be delayed for several days.

**Comment by lartpang** [comment]
@morizin 
Based on my own understanding, I implemented the [ConvAttention](https://github.com/lartpang/PyTorchCoding/blob/master/Co-Scale%20Conv-Attentional%20Image%20Transformers/ConvAttention.py) module. 
I hope it works for you.
And if you find a mistake, welcome to point it out!

**Comment by morizin** [comment]
Sure. I will start to preparing my network with this

**Comment by liqiokkk** [comment]
I am looking forward to the author's code.

**Comment by xwjabc** [comment]
Hi all, there is a version of code released today. Feel free to give it a try!
