### ISSUE TITLE
Do you have plans to release the pre-trained checkpoint for CoaT

### ISSUE THREAD

**Issue by laojiangwei** [mlpc-ucsd/CoaT#2]
Hello, It is a nice work, I find you have released the pre-trained checkpoint for CoaT-Lite. Do you have plans to release the pre-trained checkpoint for CoaT ? Thanks ~

**Comment by xwjabc** [comment]
Hi @laojiangwei, thank you for your interest in our project! We will gradually release the pre-trained checkpoints for CoaT in next week. Stay tuned!
