### ISSUE TITLE
Will CoaT Small be available?

### ISSUE THREAD

**Issue by encounter1997** [mlpc-ucsd/CoaT#6]
Dear Weijian,
I recently read your paper on CoaT, it's really excellent work!
I wish to do some further research based on CoaT Small. However, it's not mentioned in your paper or repo, so I wonder if you had implemented CoaT Small and if yes, will the model be made available? 
Thanks in advance!

**Comment by xwjabc** [comment]
Hi @encounter1997, thank you for your interest in our work! We are still working on the CoaT Small model and hopefully can release it soon. Stay tuned!
